.\"mousegrab man
.TH MOUSEGRAB 1
.SH NAME
mousegrab \- X11 app to lock mouse to a window
.SH SYNOPSIS
.B
mousegrab
.RB [options]
.SH DESCRIPTION
.B mousegrab
is a small X11 app to lock the mouse to a window and hide it:
Mouse will be hidden but buttons and mouse wheel still work, and app can
receive keystrokes. right clicking releases the mouse.

Useful if you have an optical mouse that jitters when off the floor
and you'd rather not have it wander all over the place, or you need
to click on something without worrying about mouse being moved ...
Especially nice to use with easystroke: start mousegrab with mouse gesture !

In many cases it should be a better alternative to
.RS
.nf
.B
  unclutter -idle 0 -root
.fi
.RE
to hide the mouse: no cursor flickering, and doesn't eat up cpu when mouse
is moved (however unlike unclutter, mouse isn't fully functional since
motion is disabled).


.SH OPTIONS
.TP
\fB--display\fR display
specify the display to use.
.TP
\fB-d\fR delay, \fB--delay\fR delay
wait delay seconds before grabbing mouse.
.TP
\fB--key\fR key
stop when key is pressed instead of right mouse button.
.TP
\fB--version\fR
show mousegrab version.

.SH IMPLEMENTATION
uses XGrabPointer to grab the mouse until released,
so focus etc should pretty much stay where they were when it started.
button events are forwarded to initial window.

.SH "SEE ALSO"
unclutter(1), xtrlock(1)

.SH AUTHOR
lemonsqueeze <lemonsqueeze@gmx.com>

Based on unclutter code, by Mark M Martin.
